modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
<<<<<<< HEAD
modId="reoredneoforge"
version="0.0.0.0.7"
displayName="Re-Ored-NeoForge"
=======
modId="reoredforge"
version="0.0.0.0.7"
displayName="Re-Ored"
>>>>>>> parent of bae68df (Added:-)
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Coredex"

# Start of user code block mod configuration
# End of user code block mod configuration

<<<<<<< HEAD
[[dependencies.reoredneoforge]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.reoredneoforge]]
=======
[[dependencies.reoredforge]]
>>>>>>> parent of bae68df (Added:-)
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



